server:
  port: 8080
spring:
  application:
    name: kt_rest_architecture
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: tomcat-localhost
    key-password: changeit
    key-store: classpath:keystore.jks
    key-store-provider: SUN
    key-store-type: JKS
    key-store-password: changeit
    